### PR TITLE
Add second-level domain definition to FAQ

### LINKED ISSUE #18: Define what a second-level domain is
The text of the BOD and the compliance guide refer to second-level domains, but there is never explicit guidance around what this means.

### PR DESCRIPTION
**Pull request by AntiFreeze**
Fixes #18, adds a section defining what second-level means and giving an example on how to interpret it.

### CODE REVIEW

**Comment by h-m-f-t** [comment]
Thanks for this PR, @AntiFreeze! 

I like this suggestion but think my preference is to roll this into the [`What is the scope of BOD 18-01?`](https://cyber.dhs.gov/guide/#what-is-the-scope-of-bod-18-01) question. Do you think it merits its own FAQ directly?

**Comment by h-m-f-t** [comment]
If anything, I can see the benefit in being able to link directly to an FAQ entry when `second-level domain` is used, though we could just as easily point them to the scope question.

**Comment by AntiFreeze** [comment]
I have no strong opinion either way. It definitely fits within "what is the scope," but since "second-level" is mentioned 12 times in the compliance guide, it seemed like having its own call out might be worthwhile.

**Comment by h-m-f-t** [comment]
Thanks for the suggestion, @AntiFreeze! I made a few changes and additions, but agree this is an important topic to be clear about.

**Pull request merged**
